export const appLinks: Record<string, string> = {
    // Monde 1
    Inkscape: 'https://inkscape.org',
    GIMP: 'https://www.gimp.org',
    Krita: 'https://krita.org',
    Rosegarden: 'https://www.rosegardenmusic.com',
    Audacity: 'https://www.audacityteam.org',
    Tenacity: 'https://tenacityaudio.org',
    SweetHome3D: 'http://www.sweethome3d.com',
    Blender: 'https://www.blender.org',
    OpenSCAD: 'https://openscad.org',
    Stellarium: 'https://stellarium.org',
    Celestia: 'https://celestia.space',
    'Cartes.app': 'https://umap.openstreetmap.fr/fr/',
    FreeCAD: 'https://www.freecad.org',
    BlocksCAD: 'https://www.blockscad3d.com',
    Slic3r: 'https://slic3r.org',

    // Monde 2
    Kdenlive: 'https://kdenlive.org',
    Openshot: 'https://www.openshot.org',
    OBS: 'https://obsproject.com',
    VLC: 'https://www.videolan.org/vlc/',
    HandBrake: 'https://handbrake.fr',
    Peertube: 'https://joinpeertube.org',
    NextCloud: 'https://nextcloud.com',
    Chromium: 'https://www.chromium.org',
    QRPrint: 'https://www.qr-code-generator.com/',
    uBlockOrigin: 'https://ublockorigin.com/',
    PrivacyBadger: 'https://www.eff.org/privacybadger',
    FacePrivacy: 'https://faceprivacy.com',
    Ksnip: 'https://ksnip.github.io/',
    scrcpy: 'https://github.com/Genymobile/scrcpy',
    LocalSend: 'https://localsend.org',
    CreatorDisk: 'https://www.pendrivelinux.com/universal-usb-installer-easy-as-1-2-3/',
    Logitranscribe: 'https://logitranscribe.com',

    // Monde 3
    Python: 'https://www.python.org',
    VSCodium: 'https://vscodium.com',
    Jupyter: 'https://jupyter.org',
    Scratch: 'https://scratch.mit.edu',
    GeoTortue: 'https://geotortue.education.fr',
    ArduinoIDE: 'https://www.arduino.cc/en/software',
    OpenBoard: 'https://openboard.ch/index.en.html',
    Mattermost: 'https://mattermost.com',
    doDoc: 'https://www.dodoc.fr',
    Geogebra: 'https://www.geogebra.org',
    Klavaro: 'https://klavaro.sourceforge.io',
    PortailForge: 'https://forge.education.fr',
    LaTeX: 'https://www.latex-project.org',
    LibreOffice: 'https://www.libreoffice.org',
    Scribus: 'https://www.scribus.net',
    PDFsam: 'https://pdfsam.org',
    PDF4Teachers: 'https://pdf4teachers.fr',
    Calibre: 'https://calibre-ebook.com',
    Basket: 'https://basket.kde.org',
    FreePlane: 'https://www.freeplane.org',
    gLabels: 'https://glabels.org',
};
